Controllers/ReportesController.cs
using Facturafast.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Facturafast.Controllers
{
    public class ReportesController : Controller
    {
        BD_FFEntities db;
        public ActionResult Ingresos()
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            DateTime Final = DateTime.Now;
            DateTime Inicio = new DateTime(Final.Year, Final.Month, 1);

            ViewBag.Inicio = Inicio;
            ViewBag.Final = Final;

            db = new BD_FFEntities();
            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            var lista = db.tbd_Facturas.Where(s => s.rfc_emisor == usuario.rfc && s.fecha_timbrado >= Inicio && s.fecha_timbrado <= Final).ToList();
            if (lista.Count == 0)
            {
                ViewBag.Mensaje = "No se encontraron registros.";
                ViewBag.TMensaje = "warning";
            }
            return View(lista);
        }

        [HttpPost]
        public ActionResult Ingresos(FormCollection formCollection)
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            DateTime Final = Convert.ToDateTime(formCollection["txtFechaFinal"]).AddDays(1).AddMinutes(-1);
            DateTime Inicio = Convert.ToDateTime(formCollection["txtFechaInicial"]);

            ViewBag.Inicio = Inicio;
            ViewBag.Final = Final;

            db = new BD_FFEntities();
            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            var lista = db.tbd_Facturas.Where(s => s.rfc_emisor == usuario.rfc && s.fecha_timbrado >= Inicio && s.fecha_timbrado <= Final).ToList();
            if (lista.Count == 0)
            {
                ViewBag.Mensaje = "No se encontraron registros.";
                ViewBag.TMensaje = "warning";
            }
            return View(lista);
        }

        public ActionResult Gastos()
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            DateTime Final = DateTime.Now;
            DateTime Inicio = new DateTime(Final.Year, Final.Month, 1);

            ViewBag.Inicio = Inicio;
            ViewBag.Final = Final;

            db = new BD_FFEntities();
            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            var lista = db.tbd_Facturas.Where(s => s.rfc_receptor == usuario.rfc && s.fecha_timbrado >= Inicio && s.fecha_timbrado <= Final).ToList();
            if (lista.Count == 0)
            {
                ViewBag.Mensaje = "No se encontraron registros.";
                ViewBag.TMensaje = "warning";
            }
            return View(lista);
        }

        [HttpPost]
        public ActionResult Gastos(FormCollection formCollection)
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            DateTime Final = Convert.ToDateTime(formCollection["txtFechaFinal"]).AddDays(1).AddMinutes(-1);
            DateTime Inicio = Convert.ToDateTime(formCollection["txtFechaInicial"]);

            ViewBag.Inicio = Inicio;
            ViewBag.Final = Final;

            db = new BD_FFEntities();
            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            var lista = db.tbd_Facturas.Where(s => s.rfc_receptor == usuario.rfc && s.fecha_timbrado >= Inicio && s.fecha_timbrado <= Final).ToList();
            if (lista.Count == 0)
            {
                ViewBag.Mensaje = "No se encontraron registros.";
                ViewBag.TMensaje = "warning";
            }
            return View(lista);
        }


        public ActionResult CargaXML()
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            return View();
        }

        [HttpPost]
        public String CargarArchivos(FormCollection formCollection)
        {
            if (Session["tbc_Usuarios"] == null)
                return "{\"Estatus\":0, \"Mensaje\":\"Su sesión ha expirado.\"}";

            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            foreach (string file in Request.Files)
            {
                if (Request.Files[file].ContentLength > 0)
                {
                    var File = Request.Files[file];

                    if (File.FileName.EndsWith(".xml", StringComparison.OrdinalIgnoreCase))
                    {
                        LecturaXML xml = new LecturaXML();
                        xml.LeerArchivo(File, usuario.rfc);
                    }
                }
            }
            return "{\"Estatus\":1, \"Mensaje\":\"Los datos se cargaron correctamente.\"}";
        }

        public ActionResult NotasVentas()
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            DateTime Final = DateTime.Now;
            DateTime Inicio = new DateTime(Final.Year, Final.Month, 1);

            ViewBag.Inicio = Inicio;
            ViewBag.Final = Final;

            db = new BD_FFEntities();
            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            List<ClientesNota> clientes = new List<ClientesNota>();
            var lista = db.tbd_Notas_Venta.Where(s => s.id_usuario == usuario.id_usuario && s.fecha_creacion >= Inicio && s.fecha_creacion <= Final).ToList();
            if (lista.Count == 0)
            {
                ViewBag.Mensaje = "No se encontraron registros.";
                ViewBag.TMensaje = "warning";
            }
            else
            {
                foreach (var item in lista)
                {
                    if (clientes.Where(s => s.id_cliente == item.id_cliente).Count() == 0)
                    {
                        tbc_Clientes cli = db.tbc_Clientes.Where(s => s.id_cliente == item.id_cliente).Single();
                        clientes.Add(new ClientesNota
                        {
                            id_cliente = item.id_cliente,
                            saldo_acumulado = 0,
                            nombre_razon = cli.nombre_razon,
                            num_notas = 0,
                            rfc = cli.rfc,
                            saldo_pagado = 0,
                            saldo_restante = 0
                        });
                    }

                    var actualizar = clientes.Where(s => s.id_cliente == item.id_cliente).Single();
                    if (item.id_estatus == 1)
                    {
                        actualizar.saldo_acumulado += item.total;
                        actualizar.notas_pendientes++;
                    }
                    if (item.id_estatus == 6)
                    {
                        actualizar.notas_canceladas++;
                    }
                    if (item.id_estatus == 7)
                    {
                        actualizar.saldo_acumulado += item.total;
                        //actualizar.saldo_pagado += item.total;
                        actualizar.notas_pagas++;
                    }

                    var pagos = db.tbd_Pagos_Nota_Venta.Where(s => s.id_nota_venta == item.id_nota_venta && s.fecha_pago >= Inicio && s.fecha_pago <= Final).ToList();

                    foreach (var abonos in pagos)
                    {
                        actualizar.saldo_pagado += abonos.total_pagado;
                    }

                    actualizar.num_notas++;
                    actualizar.saldo_restante = actualizar.saldo_acumulado - actualizar.saldo_pagado;
                }
            }
            return View(clientes);
        }


        [HttpPost]
        public ActionResult NotasVentas(FormCollection formCollection)
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            DateTime Final = Convert.ToDateTime(formCollection["txtFechaFinal"]).AddDays(1).AddMinutes(-1);
            DateTime Inicio = Convert.ToDateTime(formCollection["txtFechaInicial"]);

            ViewBag.Inicio = Inicio;
            ViewBag.Final = Final;

            db = new BD_FFEntities();
            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            List<ClientesNota> clientes = new List<ClientesNota>();
            var lista = db.tbd_Notas_Venta.Where(s => s.id_usuario == usuario.id_usuario && s.fecha_creacion >= Inicio && s.fecha_creacion <= Final).ToList();
            if (lista.Count == 0)
            {
                ViewBag.Mensaje = "No se encontraron registros.";
                ViewBag.TMensaje = "warning";
            }
            else
            {
                foreach (var item in lista)
                {
                    if (clientes.Where(s => s.id_cliente == item.id_cliente).Count() == 0)
                    {
                        tbc_Clientes cli = db.tbc_Clientes.Where(s => s.id_cliente == item.id_cliente).Single();
                        clientes.Add(new ClientesNota
                        {
                            id_cliente = item.id_cliente,
                            saldo_acumulado = 0,
                            nombre_razon = cli.nombre_razon,
                            num_notas = 0,
                            rfc = cli.rfc,
                            saldo_pagado = 0,
                            saldo_restante = 0
                        });
                    }


Views/Reportes/CargaXML.cshtml
<style>
    #drag_drop {
        background-color: #f9f9f9;
        border: #ccc 4px dashed;
        line-height: 250px;
        padding: 12px;
        font-size: 24px;
        text-align: center;
    }
</style>


<form method="post" action="@Url.Action("CargarArchivos","Reportes")">
    <div class="container">
        <h1 class="mt-5 mb-5 text-center text-primary"><b>Arrastra y Suelta tus archivos XML</b></h1>
        <div class="card">            
            <div class="card-body">
                <div class="row">                    
                    <div class="col-md-12">
                        <div id="drag_drop">Carga tus XML aqui</div>
                    </div>                    
                </div>
            </div>
        </div>
        <br />
        <div class="progress" id="progress_bar" style="display:none; height:50px;">
            <div class="progress-bar bg-success" id="progress_bar_process" role="progressbar" style="width:0%; height:50px;">
                0%
            </div>
        </div>
        <div id="uploaded_image" class="row mt-5"></div>
    </div>
</form>


<script>

    function _(element) {
        return document.getElementById(element);
    }

    _('drag_drop').ondragover = function (event) {
        this.style.borderColor = '#333';
        return false;
    }

    _('drag_drop').ondragleave = function (event) {
        this.style.borderColor = '#ccc';
        return false;
    }


    _('drag_drop').ondrop = function (event) {
        event.preventDefault();

        var form_data = new FormData();

        var image_number = 1;

        var error = '';

        var drop_files = event.dataTransfer.files;

        for (var count = 0; count < drop_files.length; count++) {
            if (!['text/xml'].includes(drop_files[count].type)) {
                error += '<div class="alert alert-danger" style="padding: 10px;"><b>' + image_number + '</b> &nbsp;&nbsp; Solo puede cargar archivos XML.</div>';
            }
            else {
                form_data.append("images[" + count+"]", drop_files[count]);
            }

            image_number++;
        }

        if (error != '') {
            _('uploaded_image').innerHTML = error;
            _('drag_drop').style.borderColor = '#ccc';
        }
        else {
            _('progress_bar').style.display = 'block';

            var ajax_request = new XMLHttpRequest();

            ajax_request.open("post", "@Url.Action("CargarArchivos","Reportes")");

            ajax_request.upload.addEventListener('progress', function (event) {

                var percent_completed = Math.round((event.loaded / event.total) * 100);

                _('progress_bar_process').style.width = percent_completed + '%';

                _('progress_bar_process').innerHTML = percent_completed + '% completado';

            });

            ajax_request.addEventListener('load', function (event) {

                _('uploaded_image').innerHTML = '<div class="alert alert-success" style="padding: 10px;">Archivos cargados correctamente</div>';

                _('drag_drop').style.borderColor = '#ccc';

            });

            ajax_request.send(form_data);

            ajax_request.addEventListener('readystatechange', function () {
                if (ajax_request.readyState == 3) {
                    // loading
                }
                if (ajax_request.readyState == 4) {
                    // request finished
                    var response = JSON.parse(ajax_request.response);
                    if (response.Estatus == 0) {
                        notificacionAlert(response.Mensaje, "danger");
                    }
                    else {
                        notificacionAlert(response.Mensaje, "success");
                    }
                }
            });

        }
    }

    document.addEventListener("DOMContentLoaded", function () {

    });
</script>

Views/Reportes/Gastos.cshtml
@model IEnumerable<Facturafast.Models.tbd_Facturas>
@using Facturafast.Models
@{
    BD_FFEntities db = new BD_FFEntities();
}

<h1 class="h3 mb-3">Gastos</h1>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-actions float-end">

                </div>
                <form method="post" action="@Url.Action("Gastos","Reportes")">
                    <div class="row">
                        <div class="col-md-2">

                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="date" class="form-control form-control-lg" id="txtFechaInicial" name="txtFechaInicial" placeholder="Fecha Inicial" value="@ViewBag.Inicio.ToString("yyyy-MM-dd")" required>
                                <label for="txtFechaInicial">Fecha Inicial</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="date" class="form-control form-control-lg" id="txtFechaFinal" name="txtFechaFinal" placeholder="Fecha Final" value="@ViewBag.Final.ToString("yyyy-MM-dd")" required>
                                <label for="txtFechaFinal">Fecha Final</label>
                            </div>
                        </div>
                        <div class="col-md-2">

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn btn-success btn-lg" style="margin-top:10px;"><i class="fas fa-search"></i>&nbsp; Buscar Resultados</button>
                        </div>
                    </div>
                </form>
                <br />
                <hr />
            </div>
            <div class="card-body">
                <table id="datatables-reporte-gastos" class="table table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Acciones</th>
                            <th>Nombre / Razón Social</th>
                            <th>RFC</th>
                            <th>Folio</th>
                            <th>Tipo</th>
                            <th>Fecha</th>
                            <th>Subtotal</th>
                            <th>Total</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            tbc_Tipos_Comprobante comprobante = db.tbc_Tipos_Comprobante.Where(s => s.id_tipo_comprobante == item.id_tipo_comprobante).Single();

                        <tr class="@(item.id_estatus == 6 ? "table-danger": "")">
                            <td></td>
                            <td>
                                <table>
                                    <tr>
                                        <td style="padding:0px 5px;">
                                            <a href="#" class="btn btn-danger btn-sm"><i class="fas fa-file-pdf"></i></a>
                                        </td>
                                        <td style="padding:0px 5px;">
                                            <a href="#" class="btn btn-info btn-sm"><i class="fas fa-file-archive"></i></a>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                            <td>@item.nombre_emisor</td>
                            <td>@item.rfc_emisor</td>
                            <td>@item.serie - @item.folio</td>
                            <td>@comprobante.tipo_comprobante</td>
                            <td>@item.fecha_timbrado.ToString("yyyy/MM/dd")</td>
                            <td>@item.subtotal.ToString("c")</td>
                            <td>@item.total.ToString("c")</td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        $("#datatables-reporte-gastos").DataTable({
            responsive: true,
            'columnDefs': [
                { 'sortable': false, 'searchable': false, 'visible': true, 'targets': [0, 1] }
            ],
            order: [[6, 'desc']]
        });
    });
</script>

Views/Reportes/Ingresos.cshtml
@model IEnumerable<Facturafast.Models.tbd_Facturas>
    @using Facturafast.Models
@{ 
    BD_FFEntities db = new BD_FFEntities();
}
<h1 class="h3 mb-3">Ingresos</h1>
&nbsp;
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-actions float-end">

                </div>
                <form method="post" action="@Url.Action("Ingresos","Reportes")">
                    <div class="row">
                        <div class="col-md-2">

                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="date" class="form-control form-control-lg" id="txtFechaInicial" name="txtFechaInicial" placeholder="Fecha Inicial" value="@ViewBag.Inicio.ToString("yyyy-MM-dd")" required>
                                <label for="txtFechaInicial">Fecha Inicial</label>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-floating mb-3">
                                <input type="date" class="form-control form-control-lg" id="txtFechaFinal" name="txtFechaFinal" placeholder="Fecha Final" value="@ViewBag.Final.ToString("yyyy-MM-dd")" required>
                                <label for="txtFechaFinal">Fecha Final</label>
                            </div>
                        </div>
                        <div class="col-md-2">

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn btn-success btn-lg" style="margin-top:10px;"><i class="fas fa-search"></i>&nbsp; Buscar Resultados</button>
                        </div>
                    </div>
                </form>
                <br />
                <hr />
            </div>
            <div class="card-body">
                <table id="datatables-reporte-ingresos" class="table table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Acciones</th>
                            <th>Nombre / Razón Social</th>
                            <th>RFC</th>
                            <th>Folio</th>
                            <th>Tipo</th>
                            <th>Fecha</th>
                            <th>Subtotal</th>
                            <th>Total</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                            {
                                tbc_Tipos_Comprobante comprobante = db.tbc_Tipos_Comprobante.Where(s => s.id_tipo_comprobante == item.id_tipo_comprobante).Single();

                            <tr class="@(item.id_estatus == 6 ? "table-danger": "")">
                                <td></td>
                                <td>
                                    <table>
                                        <tr>
                                            <td style="padding:0px 5px;">
                                                <a href="#" class="btn btn-danger btn-sm"><i class="fas fa-file-pdf"></i></a>
                                            </td>
                                            <td style="padding:0px 5px;">
                                                <a href="#" class="btn btn-info btn-sm"><i class="fas fa-file-archive"></i></a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                                <td>@item.nombre_receptor</td>
                                <td>@item.rfc_receptor</td>
                                <td>@item.serie - @item.folio</td>
                                <td>@comprobante.tipo_comprobante</td>
                                <td>@item.fecha_timbrado.ToString("yyyy/MM/dd")</td>
                                <td>@item.subtotal.ToString("c")</td>
                                <td>@item.total.ToString("c")</td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        $("#datatables-reporte-ingresos").DataTable({
            responsive: true,
            'columnDefs': [
                { 'sortable': false, 'searchable': false, 'visible': true, 'targets': [0, 1] }
            ],
            order: [[6, 'desc']]
        });
    });
</script>

Views/Reportes/Nominas.cshtml
<h1 class="h3 mb-3">Nóminas</h1>


<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="card-actions float-end">

                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control form-control-lg" id="txtFechaInicial" placeholder="Fecha Inicial">
                            <label for="txtFechaInicial">Fecha Inicial</label>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control form-control-lg" id="txtFechaFinal" placeholder="Fecha Final">
                            <label for="txtFechaFinal">Fecha Final</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <a class="btn btn-success btn-lg" style="margin-top:10px;"><i class="fas fa-search"></i>&nbsp; Buscar Nóminas</a>
                    </div>
                </div>
                <hr />
            </div>
            <div class="card-body">
                <table id="datatables-reporte-gastos" class="table table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Acciones</th>
                            <th>No. de Empleado</th>
                            <th>Nombre del Empleado</th>
                            <th>RFC</th>
                            <th>CURP</th>
                            <th>NSS</th>
                            <th>Teléfono</th>
                            <th>Tipo</th>
                            <th>Fecha</th>
                            <th>Dias Pagados</th>
                            <th>Periodicidad</th>
                            <th>Subtotal</th>
                            <th>Total</th>

                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td><a href="#" class="btn btn-danger btn-sm"><i class="fas fa-file-pdf"></i></a> &nbsp;&nbsp; <a href="#" class="btn btn-info btn-sm"><i class="fas fa-file-archive"></i></a></td>
                            <td>Emp-001</td>
                            <td>Rene Josec Meza Arzave</td>
                            <td>XAXX010101000</td>
                            <td>XAXX010101HBCZRN06</td>
                            <td>2637483746</td>
                            <td>2223415134</td>
                            <td>N - Nómina</td>
                            <td>01/02/2022</td>
                            <td>15</td>
                            <td>04 - Quincenal</td>
                            <td>$100.00</td>
                            <td>$116.00</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script>
    document.addEventListener("DOMContentLoaded", function () {
        $("#datatables-reporte-gastos").DataTable({
            responsive: true,
            'columnDefs': [
                { 'sortable': false, 'searchable': false, 'visible': true, 'targets': [0, 1] }
            ],
            order: [[2, 'asc']]
        });

        $("input[id=\"txtFechaInicial\"]").daterangepicker({
            singleDatePicker: true,
            showDropdowns: true
        });
        $("input[id=\"txtFechaFinal\"]").daterangepicker({
            singleDatePicker: true,
            showDropdowns: true
        });
    });
</script>