Controllers/FacturacionController.cs
using Facturafast.CLS40;
using Facturafast.Models;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Word = Microsoft.Office.Interop.Word;

namespace Facturafast.Controllers
{
    public class FacturacionController : Controller
    {
        BD_FFEntities db;
        // Vista ListFactura
        public ActionResult ListaFactura()
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            if (TempData["Mensaje"] != null)
            {
                ViewBag.Mensaje = TempData["Mensaje"];
                ViewBag.TMensaje = TempData["TMensaje"];
            }
            DateTime Final = DateTime.Now.AddDays(1);
            DateTime Inicio = new DateTime(Final.Year, Final.Month, 1);

            ViewBag.Inicio = Inicio;
            ViewBag.Final = Final;
            return View();
                            
            //db.tbd_Pre_Factura.Where(s => s.rfc_usuario == usuario.rfc && s.fecha_emision >= Inicio && s.fecha_emision <= Final && s.status != 0 && s.tipo == "Factura").ToList();

        }
        //Vista Conceptos
        public ActionResult ListaComplemento()
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            if (TempData["Mensaje"] != null)
            {
                ViewBag.Mensaje = TempData["Mensaje"];
                ViewBag.TMensaje = TempData["TMensaje"];
            }
            DateTime Final = DateTime.Now.AddDays(1);
            DateTime Inicio = new DateTime(Final.Year, Final.Month, 1);

            ViewBag.Inicio = Inicio;
            ViewBag.Final = Final;
            return View();
        }
        //Vista Form Factura
        public ActionResult Factura(Int32? id = 0)
        {
            if (id == 0)
            {
                ViewBag.id = 0;
                return View();
            }
            else
            {
                ViewBag.id = id;
                return View(id);
            }
        }
        public ActionResult Complemento(Int32? id = 0)
        {
            if (id == 0)
            {
                ViewBag.id = 0;
                return View();
            }
            else
            {
                ViewBag.id = id;
                return View(id);
            }
        }
        public ActionResult TimbrarFac(Int32? id)
        {
            if (Session["tbc_Usuarios"] == null)
                return RedirectToAction("Inicio", "Sesion");

            if (id == null)
                return RedirectToAction("Clientes", "Catalogos");

            if (TempData["Mensaje"] != null)
            {
                ViewBag.Mensaje = TempData["Mensaje"];
                ViewBag.TMensaje = TempData["TMensaje"];
            }

            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            db = new BD_FFEntities();
            var factura = db.tbd_Pre_Factura.Where(s => s.id_pre_factura == id).Single();
            ViewBag.IdPreFactura = factura;
            ViewBag.Estatus = factura.status;
            return View(factura);
        }
        public ActionResult saveFactura(List<PreFactura> prefactura, List<CfdiUuid> uuid, List<ConceptosPreFactura> concepto, Int32? id_pre_factura)
        {

            tbc_Usuarios usuario = Session["tbc_Usuarios"] as tbc_Usuarios;
            db = new BD_FFEntities();
            int id_pre_fac = 0;
            foreach (var item in prefactura)
            {
                decimal subtotal_ = Math.Round(Convert.ToDecimal(item.subtotal), 2);
                string subtotal = subtotal_.ToString();//Regex.Replace(prefac.subtotal, ",", "");
                                                       //subtotal = subtotal.Substring(1);

                decimal total_iva_ = Math.Round(Convert.ToDecimal(item.total_iva), 2);
                string total_iva = total_iva_.ToString();

                decimal total_iva_ret_ = Math.Round(Convert.ToDecimal(item.total_iva_ret), 2);
                string total_iva_ret = total_iva_ret_.ToString();

                decimal total_isr_ret_ = Math.Round(Convert.ToDecimal(item.total_isr_ret), 2);
                string total_isr_ret = total_isr_ret_.ToString();

                decimal descuento2_ = item.descuento2 == null ? 0 : Math.Round(Convert.ToDecimal(item.descuento2), 2);
                string descuento2 = descuento2_.ToString();

                decimal total_ = Math.Round(Convert.ToDecimal(item.total), 2);
                string total = total_.ToString();
                DateTime fecha_emision = Convert.ToDateTime(item.fecha_emision);
                var reg = db.tbc_Regimenes.Where(s => s.id_regimen_fiscal == usuario.id_regimen_fiscal).Single();
                tbd_Pre_Factura nuevaPre = new tbd_Pre_Factura
                {
                    id_usuario = usuario.id_usuario,
                    rfc_usuario = usuario.rfc,
                    nombre_usuario_rfc = usuario.nombre_razon,
                    serie = item.serie,
                    folio = item.folio,
                    tipo_comprobante = item.tipo_comprobante,
                    exportacion = item.exportacion,
                    reg_fiscal_usuario = reg.clave.ToString(),
                    rfc_cliente = item.rfc_cliente_pf,
                    nombre_rfc = item.nombre_rfc_pf,
                    uso_factura = item.uso_factura,
                    clave_reg_fiscal = item.clave_reg_fiscal,
                    clave_uso_cfdi = item.clave_uso_cfdi,
                    lugar_expedicion = item.lugar_expedicion,
                    tipo_factura = item.tipo_factura,
                    forma_pago = item.forma_pago,
                    metodo_pago = item.metodo_pago,
                    numero_pedido = item.numero_pedido == null ? "" : item.numero_pedido,
                    moneda = item.moneda,
                    tipo_cambio = item.tipo_cambio == null ? "" : item.tipo_cambio,
                    fecha_emision = fecha_emision,
                    numero_cuenta = item.numero_cuenta == null ? "" : item.numero_cuenta,
                    nom_banco = item.nom_banco == null ? "" : item.nom_banco,
                    cond_pago = item.cond_pago == null ? "" : item.cond_pago,
                    cuenta_predial = item.cuenta_predial == null ? "" : item.cuenta_predial,
                    observacion = item.observacion == null ? "" : item.observacion,
                    subtotal = subtotal,
                    total_iva = total_iva,
                    total_iva_ret = total_iva_ret,
                    total_isr_ret = total_isr_ret,
                    descuento2 = descuento2 == "0.00" ? "" : descuento2,
                    total = total,
                    total_imp_ret = total,
                    status = 1,
                    tipo = "Factura"
                };
                db.tbd_Pre_Factura.Add(nuevaPre);
                db.SaveChanges();
                id_pre_fac = nuevaPre.id_pre_factura;
            }
            if (uuid != null)
            {
                foreach (var item in uuid)
                {
                    tbd_Cfdi_Uuid nuevoUuid = new tbd_Cfdi_Uuid
                    {
                        id_pre_factura = id_pre_fac,
                        id_relacion = item.id_relacion,
                        uuid = item.uuid
                    };
                    db.tbd_Cfdi_Uuid.Add(nuevoUuid);
                    db.SaveChanges();
                }
            }
            if (concepto != null)
            {
                foreach (var item in concepto)
                {
                    var clv_prod = db.tbc_ProdServ.Where(u => u.id_sat == item.id_sat).Select(u => u.c_pord_serv).First();
                    tbd_Conceptos_Pre_Factura nuevoConceptoPF = new tbd_Conceptos_Pre_Factura
                    {
                        id_pre_factura = id_pre_fac,
                        c_prod_serv = clv_prod,//item.c_prod_serv,
                        c_producto = item.c_producto,
                        id_sat = item.id_sat,
                        cantidad = item.cantidad,
                        c_unidad_medida = item.c_unidad_medida,
                        unidad = item.unidad,
                        concepto = item.concepto,
                        importe_unitario = item.importe_unitario,
                        importe_total = item.importe_total,
                        descuento = item.descuento == null ? "" : item.descuento,
                        obj_impuesto = item.obj_impuesto,
                        iva_imp_traslado = item.iva_imp_traslado,
                        tipo_factor = item.tipo_factor,
                        iva_tasa = item.iva_tasa,
                        iva_tasa_impuesto = item.iva_tasa_impuesto,
                        iva_ret = item.iva_ret,
                        iva_ret_tasa = item.iva_ret_tasa,
                        iva_ret_impuesto = item.iva_ret_impuesto,
                        isr_ret = item.isr_ret,
                        isr_ret_tasa = item.isr_ret_tasa,
                        isr_ret_impuesto = item.isr_ret_impuesto,
                        tipo_ieps = item.tipo_ieps,
                        ieps = item.ieps == null ? "" : item.ieps,
                        v_ieps = item.v_ieps == null ? "" : item.v_ieps,

Views/Facturacion/ComplementoPreview.cshtml
@using Facturafast.Models
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<input type="hidden" id="tmp_pdf" />
<input type="hidden" id="tmp_xml" />
<h1 class="h3 mb-3">PrePagos</h1>
<div class="row">
    <div class="col-md-2 col-xs-2">
        <input type="hidden" value="@ViewBag.ID" id="idprepago" />
        <button class="btn btn-danger btnEstatus mb-3" id="btnTimbrar" style="visibility:hidden" onclick="timbrarModal()">Timbrar</button><br />
        <a class="btn btn-warning btnPrePago mb-3" id="btnEditar" href="/Facturacion/Complemento?id=@ViewBag.ID" style="visibility: hidden"><i class="fas fa-edit"></i> Editar</a><br />
        <a class="btn btn-success btnPrePago" id="btnListar" href='/Facturacion/ListaComplemento' style="visibility: hidden"><i class="fas fa-file-alt"></i> Listar</a>
    </div>
    <div class="col-md-10 col-xs-10" id="d_prepagos" style="visibility:hidden">
        <div class="card">
            <div class="card-header">

            </div>
            <div class="row rpdf">

            </div>
        </div>
    </div>
</div>
<!-- MODAL FACTS -->
<div class="modal fade" id="modalTimbrado" tabindex="-1" role="dialog" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Timbrar</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body m-3">
                <input type="hidden" id="idprefac_modal" />
                <input type="hidden" id="correo_cliente" />
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-floating mb-4">
                            <input type="text" class="form-control form-control-lg text-uppercase" readonly id="rfc_receptor">
                            <label for="rfc_emisor">RFC</label>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="form-floating mb-4">
                            <input type="text" class="form-control form-control-lg text-uppercase" readonly id="razon_recpetor">
                            <label for="razon_emisor">Razón Social</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-floating mb-4">
                            <input type="text" class="form-control form-control-lg text-uppercase" readonly id="total">
                            <label for="total">Total</label>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="timbrar()" id="btnTimbre"><i class="fas fa-bell"></i>&nbsp; Timbrar</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="btnCerrar"><i class="fas fa-remove"></i>&nbsp; Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script>
    setTimeout(function () { abrirCargando(); previsualizar(0); }, 1000);
    const id = '@ViewBag.ID';
    const estatus_ = '@ViewBag.Estatus'
    function previsualizar(a)
    {
        console.log("-->"+a);
        $("#d_prepagos").css("visibility", "visible");
        $(".rpdf").empty();
        //-------------------------------------------------------------------------
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            url: '/Facturacion/VisPrePagos?id=' + id,
            data: JSON.stringify({ 'id': id }),
            success: function (data) {
                var response = data;
                if (response == "NG") {
                    previsualizar(0);
                }
                else {
                    var aux_path = response.split("/");
                    if (aux_path[0] == "Cancelado") {
                        $("#btnTimbrar").attr('disabled',true);

                    } else {
                        $("#btnTimbrar").attr('disabled', false);
                        f_pdf = response;
                        $(".rpdf").html('<iframe src="/' + response + '" style="height:100vh"></iframe>');
                        $("#tmp_pdf").val(response);
                        //setTimeout(function () {
                        if ('@ViewBag.Estatus' == "1" && a == 0) {
                            $(".btnPrePago").css("visibility", "visible");
                            $(".btnEstatus").css("visibility", "visible");
                            $("#btnListar").css("visibility", "visible");
                            genXML(id);
                        } else {
                            $(".btnEstatus").css("visibility", "hidden");
                            $(".btnPrePago").css("visibility", "hidden");
                            $("#btnListar").css("visibility", "visible");
                        }
                        if (a == 1)
                        {
                            $(".btnEstatus").css("visibility", "hidden");
                            $(".btnPrePago").css("visibility", "hidden");
                            $("#btnListar").css("visibility", "visible");
                            genBtn();
                        }
                        
                        f_doc = f_pdf.replace('PDF', 'DOCX');
                        f_doc = f_doc.replace('.pdf', '.docx');
                    }
                    cerrarCargando();
                    //}, 15000);
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                notificacionAlert("Ocurrio un error, vuelva a intentar", "danger");
                cerrarCargando();
            }
        });
        //-------------------------------------------------------------------------
    }

    function timbrarModal()
    {

        $("#idprefac_modal").val('@ViewBag.ID');
        bootstrap.Modal.getOrCreateInstance(document.getElementById("modalTimbrado")).show();
        $.get("@Url.Action("getPrePagoID", "Facturacion")?id=" + id, async function (data) {
            $("#correo_cliente").val(data.correo);
            $("#total").val(formatoMoneda(data.total));
            $("#razon_recpetor").val(data.nombre_razon);
            $("#rfc_receptor").val(data.rfc);
        });
    }

    function timbrar()
    {
        $("#btnTimbre").html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span><span class= "sr-only">Loading...</span>');
        $("#btnCerrar").css("disabled",true);

        let id = $("#idprefac_modal").val();
        abrirCargando();
        $("#btnPreTimbrar").css("display", "block");
        $("#btnTimbrar").css("display", "none");
        //-------------------------------------------------------------------------
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            url: '/XML/TimbrarXML?id_=' + id,
            data: JSON.stringify({ 'id_': id,'n_doc':'Fac_Pago.xml', 'tipo':'Pago' }),
            success: function (data) {
                var response = data;
                response = response.split("|");
                if (response[0] == "Timbrado" || response[0] =="Timdrado") {
                    notificacionAlert("Timbrada Correctamente", "success");
                    $("#btnEditar").css('visibility', 'hidden');
                    $("#btnTimbrar").css('visibility', 'hidden');
                    previsualizar(1);
                    cerrarCargando();
                } else {
                    notificacionAlert("Ocurrio un error, " + response[2] + ",vuelva a intentar", "danger");
                    cerrarCargando();
                }

            },
            error: function (jqXHR, textStatus, errorThrown) {
                notificacionAlert("Ocurrio un error, vuelva a intentar", "danger");
                cerrarCargando();
            }
        });
        //$("#btnEditar").css('visibility', 'hidden');
        //            $("#btnTimbrar").css('visibility', 'hidden');
        //            previsualizar(1);
        //            cerrarCargando();
        //-------------------------------------------------------------------------
    }

    function sendcorreo()
    {
        abrirCargando();
        let correo = $("#correo_cliente").val();
        let id = $("#idprefac_modal").val();
        //-------------------------------------------------------------------------
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            url: '/Facturacion/EnviarCorreo',
            data: JSON.stringify({ 'id_': id, 'correo_': correo, 'tipo': 'Prepago'}),
            success: function (data) {
                var response = data;
                console.log(response);
                cerrarCargando();
                if (response == "Enviado") {
                    notificacionAlert("Correo enviado satisfactoriamente.", "success");
                    setTimeout(function () { window.location = '@Url.Action("ListaComplemento", "Facturacion")' }, 3000);
                } else {
                    notificacionAlert("Ocurrio un problema al enviar el correo, intentelo mas tarde.", "danger");
                }
            },
            error: function (jqXHR, textStatus, errorThrown) {
                notificacionAlert("Ocurrio un error, vuelva a intentar", "danger");
                cerrarCargando();
            }
        });
        //-------------------------------------------------------------------------
    }

    function genXML(id)
    {
        //-------------------------------------------------------------------------
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            url: '/XML/genPagoXML?id=' + id,
            data: JSON.stringify({ 'id': id }),
            success: function (data) {
                var response = data;
                console.log(response);

            },
            error: function (jqXHR, textStatus, errorThrown) {
                //notificacionAlert("Ocurrio un error, vuelva a intentar", "danger");
                cerrarCargando();
            }
        });
        //-------------------------------------------------------------------------
    }

    function genBtn()
    {
        $("#btnTimbrar").css('visibility', 'hidden');
        var rutaPDF = $("#tmp_pdf").val();
        var rxml_tmp = rutaPDF.split("/");
        var nombre_f = rxml_tmp[6].split(".");
        var r_temp_xml = rxml_tmp[0] + "/" + rxml_tmp[1] + "/" + rxml_tmp[2] + "/" + rxml_tmp[3] + "/" + rxml_tmp[4] + "/" + rxml_tmp[5] + "/" + nombre_f[0] + ".xml";
        $("#tmp_xml").val(r_temp_xml);
        var rutaXML = r_temp_xml;
        $(".modal-footer").empty();
        $(".modal-footer").html('<button class="btn btn-primary" onclick=sendcorreo()><i class="fas fa-envelope"></i>&nbsp; Enviar Correo</button>' +
            '<a target="_blank" class="btn btn-success" href="../' + rutaPDF + '"><i class="fas fa-file"></i>&nbsp; Descargar PDF</button>' +
            '<a class="btn btn-info" href="../' + rutaXML + '"><i class="fas fa-file"></i>&nbsp; Descargar XML</button>');
    }
</script>